### ISSUE TITLE
what did you execute this using?

### ISSUE THREAD

**Issue by sadavarterohit** [r1ghtwr0ng/ARM_hangman#1]
Did you execute the program using qemu, on a pi directly or any other method?

**Comment by r1ghtwr0ng** [comment]
> Did you execute the program using qemu, on a pi directly or any other method?

It was a uni project, so I ran it on an ARM remote machine they had set up (I believe it was a physical raspberry pi, however I am not 100% sure). Make sure you compile and assemble as a 32-bit executable if you're planning on running it. 
Cheers!
