### ISSUE TITLE
WHEN SUPPORT FOR CONTROLLER?

### ISSUE THREAD

**Issue by martinteoharov** [r1ghtwr0ng/ARM_hangman#5]
Is the dev an absolute dickhead that is busy watching midgets fuck in his backyard????

**Comment by r1ghtwr0ng** [comment]
# NIGHTMARE NIGHTMARE NIGHTMARE NIGHTMARE NIGHTMARE NIGHTMARE NIGHTMARE NIGHTMARE
Its in the backlog, just like how I'm in your walls.
Please submit future complaints to https://martinteoharov.com/ or implement it yourself and open a PR
